inforegistry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  volumes:
    - MY_SHARED_HOST_FOLDER:/var/lib/registry

registryui: 
  image: hyper/docker-registry-web
  environment:
    REGISTRY_HOST: CHANGE_ME_HOST_NAME
    REGISTRY_PORT: 5000
    REGISTRY_AUTH: "YWRtaW46Y2hhbmdlbWU="
  ports:
    - CHANGE_ME_PORT_ON_HOST:8080 